---
- hosts: leaf1-DC1
  gather_facts: no
  tasks:
  - name: Register variables
    include_vars:
      file: "{{lookup('env','PWD')}}/vars/underlay-DC1.yaml"
      name: underlay
  - name: Create a configuration for Ethernet3
    template:
      src: "{{lookup('env','PWD')}}/templates/interface.j2"
      dest: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_interface.cfg"