- hosts: all
  gather_facts: no
  tasks:
    - name: Add User
      eos_user:
        name: automator 
        nopassword: yes
        privilege: 15
        role: network-admin
        state: present
    - name: Add SSH key
      eos_command:
        commands: 
          - "config"
          - "username automator ssh-key {{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      register: "output"
    
    # - debug:
    #     msg: "{{ output }}"